import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HalamanLogin(),
        ]),
      ),
    );
  }
}

class HalamanLogin extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 440,
          height: 956,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 17,
                child: Container(
                  width: 440,
                  height: 941,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 33,
                        top: 36,
                        child: Container(
                          width: 375,
                          height: 276,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 80,
                                child: Container(
                                  width: 327,
                                  height: 164,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 123.50,
                                        top: 0,
                                        child: Container(
                                          width: 80,
                                          height: 80,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF2D50EE),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(16),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 26.88,
                                                top: 22,
                                                child: Container(
                                                  width: 26.25,
                                                  height: 36,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 2.75,
                                                        child: Container(
                                                          width: 26.25,
                                                          height: 30,
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Container(
                                                                width: 26.25,
                                                                height: 30,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: ShapeDecoration(
                                                                  color: Colors.black.withValues(alpha: 0),
                                                                  shape: RoundedRectangleBorder(
                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                  ),
                                                                ),
                                                                child: Stack(),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 108,
                                        child: SizedBox(
                                          width: 327,
                                          height: 32,
                                          child: Text(
                                            'PolyCanteen',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF1A1A1A),
                                              fontSize: 24,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w700,
                                              height: 1.33,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 143,
                                        child: SizedBox(
                                          width: 327,
                                          height: 20,
                                          child: Text(
                                            'Masuk untuk melanjutkan',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF757575),
                                              fontSize: 14,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.43,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 322,
                        child: Container(
                          width: 375,
                          height: 320,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 0,
                                child: Container(
                                  width: 327,
                                  height: 296,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 327,
                                          height: 82,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 327,
                                                  height: 20,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 1,
                                                        child: SizedBox(
                                                          width: 327,
                                                          height: 20,
                                                          child: Text(
                                                            'Nomor Handphone',
                                                            style: TextStyle(
                                                              color: const Color(0xFF1A1A1A),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w500,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 28,
                                                child: Container(
                                                  width: 327,
                                                  height: 54,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 327,
                                                          height: 54,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(
                                                                width: 1,
                                                                color: const Color(0xFFE5E7EB),
                                                              ),
                                                              borderRadius: BorderRadius.circular(12),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 64,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 327,
                                                                  height: 54,
                                                                  child: Text(
                                                                    '81234567890',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFFADAEBC),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1.43,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 16,
                                                        top: 17,
                                                        child: Container(
                                                          width: 39.48,
                                                          height: 20,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 27,
                                                                  height: 20,
                                                                  child: Text(
                                                                    '+62',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFF757575),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1.43,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 38.48,
                                                                top: 2,
                                                                child: Container(
                                                                  width: 1,
                                                                  height: 16,
                                                                  decoration: ShapeDecoration(
                                                                    color: const Color(0xFFD1D5DB),
                                                                    shape: RoundedRectangleBorder(
                                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 93,
                                        child: Container(
                                          width: 327,
                                          height: 82,
                                          decoration: ShapeDecoration(
                                            color: Colors.black.withValues(alpha: 0),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 327,
                                                  height: 20,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 1,
                                                        child: SizedBox(
                                                          width: 327,
                                                          height: 20,
                                                          child: Text(
                                                            'Kata Sandi',
                                                            style: TextStyle(
                                                              color: const Color(0xFF1A1A1A),
                                                              fontSize: 14,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w500,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 28,
                                                child: Container(
                                                  width: 327,
                                                  height: 54,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.black.withValues(alpha: 0),
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                    ),
                                                  ),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 327,
                                                          height: 54,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(
                                                                width: 1,
                                                                color: const Color(0xFFE5E7EB),
                                                              ),
                                                              borderRadius: BorderRadius.circular(12),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 16,
                                                                top: 0,
                                                                child: SizedBox(
                                                                  width: 327,
                                                                  height: 54,
                                                                  child: Text(
                                                                    'Masukkan kata sandi',
                                                                    style: TextStyle(
                                                                      color: const Color(0xFFADAEBC),
                                                                      fontSize: 14,
                                                                      fontFamily: 'Inter',
                                                                      fontWeight: FontWeight.w400,
                                                                      height: 1.43,
                                                                    ),
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 293,
                                                        top: 15,
                                                        child: Container(
                                                          width: 18,
                                                          height: 24,
                                                          decoration: ShapeDecoration(
                                                            color: Colors.black.withValues(alpha: 0),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                            ),
                                                          ),
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 2,
                                                                child: Container(
                                                                  width: 18,
                                                                  height: 20,
                                                                  decoration: ShapeDecoration(
                                                                    color: Colors.black.withValues(alpha: 0),
                                                                    shape: RoundedRectangleBorder(
                                                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                    ),
                                                                  ),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 2,
                                                                        child: Container(
                                                                          width: 18,
                                                                          height: 16,
                                                                          child: Row(
                                                                            mainAxisSize: MainAxisSize.min,
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                                            children: [
                                                                              Container(
                                                                                width: 18,
                                                                                height: 16,
                                                                                clipBehavior: Clip.antiAlias,
                                                                                decoration: ShapeDecoration(
                                                                                  color: Colors.black.withValues(alpha: 0),
                                                                                  shape: RoundedRectangleBorder(
                                                                                    side: BorderSide(color: const Color(0xFFE5E7EB)),
                                                                                  ),
                                                                                ),
                                                                                child: Stack(),
                                                                              ),
                                                                            ],
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 28,
                                        top: 225,
                                        child: Container(
                                          width: 265,
                                          height: 52,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF2D50EE),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                          ),
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 16,
                                                child: SizedBox(
                                                  width: 265,
                                                  height: 20,
                                                  child: Text(
                                                    'Masuk',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: Colors.white,
                                                      fontSize: 14,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w600,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 676,
                        child: Container(
                          width: 375,
                          height: 108,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 33,
                                child: SizedBox(
                                  width: 327,
                                  height: 20,
                                  child: Text(
                                    'Belum punya akun?',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF757575),
                                      fontSize: 14,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.43,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 53,
                                child: Container(
                                  width: 327,
                                  height: 24,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(color: const Color(0xFFE5E7EB)),
                                    ),
                                  ),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 2,
                                        child: SizedBox(
                                          width: 327,
                                          height: 24,
                                          child: Text(
                                            'Daftar sekarang',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF2D50EE),
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 748,
                        child: Container(
                          width: 375,
                          height: 147.50,
                          decoration: ShapeDecoration(
                            color: Colors.black.withValues(alpha: 0),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: const Color(0xFFE5E7EB)),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 151,
                        top: 930,
                        child: Container(
                          width: 138,
                          height: 3,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF757575),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.20,
                                strokeAlign: BorderSide.strokeAlignOutside,
                                color: const Color(0xFF888888),
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 440,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 401.33,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              color: Colors.black,
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 403.33,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 9,
                        top: 8,
                        child: Container(
                          width: 63.36,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 5.33,
                                child: SizedBox(
                                  width: 63,
                                  child: Text(
                                    '9:41',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'SF Pro Text',
                                      fontWeight: FontWeight.w600,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}