org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=128m -XX:+HeapDumpOnOutOfMemoryError -Xss512k
org.gradle.workers.max=2
org.gradle.parallel=true
android.useAndroidX=true
android.enableR8.fullMode=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
