// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAZ-92uCuHP7AA5KLurdHx8QAbSLbzVI',
    appId: '1:191706147557:web:8341f40fc4a513497dc20c',
    messagingSenderId: '191706147557',
    projectId: 'polycanteen-db-1a9d3',
    authDomain: 'polycanteen-db-1a9d3.firebaseapp.com',
    storageBucket: 'polycanteen-db-1a9d3.firebasestorage.app',
    measurementId: 'G-549HCH8MFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdi4-kE0NU9F6nf6zkGKLlfI7sKFAMuY',
    appId: '1:191706147557:android:169bc3a13088c78a7dc20c',
    messagingSenderId: '191706147557',
    projectId: 'polycanteen-db-1a9d3',
    storageBucket: 'polycanteen-db-1a9d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9DxqB2uT3c9JtCk-7DaL6Cyv45ItK3gk',
    appId: '1:191706147557:ios:2efb8ef9320b576f7dc20c',
    messagingSenderId: '191706147557',
    projectId: 'polycanteen-db-1a9d3',
    storageBucket: 'polycanteen-db-1a9d3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9DxqB2uT3c9JtCk-7DaL6Cyv45ItK3gk',
    appId: '1:191706147557:ios:2efb8ef9320b576f7dc20c',
    messagingSenderId: '191706147557',
    projectId: 'polycanteen-db-1a9d3',
    storageBucket: 'polycanteen-db-1a9d3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqAZ-92uCuHP7AA5KLurdHx8QAbSLbzVI',
    appId: '1:191706147557:web:5e22499a711fe77c7dc20c',
    messagingSenderId: '191706147557',
    projectId: 'polycanteen-db-1a9d3',
    authDomain: 'polycanteen-db-1a9d3.firebaseapp.com',
    storageBucket: 'polycanteen-db-1a9d3.firebasestorage.app',
    measurementId: 'G-GSRY82KV2L',
  );

}