// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfTOtizMwAHUdZpQlQmajdvGpDtbKOoRw',
    appId: '1:935228298100:web:51775fbf4243ed09edd221',
    messagingSenderId: '935228298100',
    projectId: 'polycanteen-db',
    authDomain: 'polycanteen-db.firebaseapp.com',
    storageBucket: 'polycanteen-db.firebasestorage.app',
    measurementId: 'G-93F1M391VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6j6Hh-pksRnxwib0qmpvR2C3Vo4w2xu8',
    appId: '1:935228298100:android:77ed7eb9270a4ddaedd221',
    messagingSenderId: '935228298100',
    projectId: 'polycanteen-db',
    storageBucket: 'polycanteen-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQH5Fv1-NVj28nX5Ny5ZUMY96rUCRXyQ',
    appId: '1:935228298100:ios:d9b841d3b88c81a7edd221',
    messagingSenderId: '935228298100',
    projectId: 'polycanteen-db',
    storageBucket: 'polycanteen-db.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQH5Fv1-NVj28nX5Ny5ZUMY96rUCRXyQ',
    appId: '1:935228298100:ios:d9b841d3b88c81a7edd221',
    messagingSenderId: '935228298100',
    projectId: 'polycanteen-db',
    storageBucket: 'polycanteen-db.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfTOtizMwAHUdZpQlQmajdvGpDtbKOoRw',
    appId: '1:935228298100:web:840ecc9bce365950edd221',
    messagingSenderId: '935228298100',
    projectId: 'polycanteen-db',
    authDomain: 'polycanteen-db.firebaseapp.com',
    storageBucket: 'polycanteen-db.firebasestorage.app',
    measurementId: 'G-W5QNR6CV3D',
  );
}
